[project]
name = "ansible-ssh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible-core>=2.18.2",
    "ansible-lint>=25.1.2",
    "yamllint>=1.35.1",
]
